server:
  port: 8761

eureka:
  instance:
    hostname: dungdang3162.cybersoft.vn
    preferIpAddress: true
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/